spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahn479512@gmail.com
    password: jin89434795


  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: false
  output:
    ansi:
      enabled: always