package welper.welper.domain.attribute

enum class Category(val value: String, val code:String) {
    INFANTS("영유아","&lifeArray=001"),
    CHILD("아동","&lifeArray=002"),
    TEENAGE("청소년","&lifeArray=003"),
    YOUTH("청년","&lifeArray=004"),
    MIDDLEAGE("중장년","&lifeArray=005"),
    OLDAGE("노년","&lifeArray=006"),
    CHARACTERISTICNOT("특성없음","&charTrgterArray=001"),
    WOMEN("여성","&charTrgterArray=002"),
    PREGNENT("임산부","&charTrgterArray=003"),
    DISORDER("장애인","&charTrgterArray=004"),
    NATIONALMERIT("국가유공자","&charTrgterArray=005"),
    UNEMPLOYED("실업자","&charTrgterArray=006"),
    SERVE("심한","&obstAbtArray=10"),
    WEAK("약한","&obstAbtArray=20"),
    TRGTERINDVDLDONOT("가구없음","&trgterIndvdlArray=001"),
    SINGLEPARENTS("한부모","&trgterIndvdlArray=002") ,
    MULTICULTURE("다문화","&trgterIndvdlArray=003"),
    GRANDCHILDREN("조손","&trgterIndvdlArray=004"),
    SETTERMIN("새터민","&trgterIndvdlArray=005"),
    CHILDHEAD("소년소녀가장","&trgterIndvdlArray=006"),
    SOLOOLD("독거노인","&trgterIndvdlArray=007"),
    SAFETY("안전","&desireArray=0000000"),
    HEALTH("건강","&desireArray=1000000"),
    DAILYLIFE("일상생활유지","&desireArray=2000000"),
    FAMIlY("가족관계","&desireArray=3000000"),
    SOCIAL("사회적 관계","&desireArray=4000000"),
    ECONOMIC("경제","&desireArray=5000000"),
    EDUCATION("교육","&desireArray=6000000"),
    EMPLOYMENT("고용","&desireArray=7000000"),
    LIFE("생활환경","&desireArray=8000000"),
    LAW("법","&desireArray=9000000"),
    ELSE("기타","&desireArray=A000000"),
    NONE("빈값","")
}
